version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  backend:
    build: .
    user: "node"
    environment:
      - MONGODB_CONNECTION=mongodb://root:root@mongo:27017
    volumes:
      - ./backend:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    user: "node"
    environment:
      - API_HOST=http://backend:3000
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3001:3000"
    command: "npm start"

